### ISSUE TITLE
`cookie::Cookie<'_>` and `Cookie<'_>` have similar names, but are actually distinct types

### ISSUE THREAD

**Issue by sameul2012** [ntex-rs/ntex#191]
steps:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/106046511/227427257-854f3c05-7da0-4bba-8c85-32b1b69065ef.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/106046511/227427442-1599ae70-3fc0-4a29-82cf-3dabd2262274.png">

```rust
use cookie::{time::Duration, Cookie};
use ntex::{
    http::Response,
    web::{
        types::{Json, State},
        Responder, 
    },
};

use reqwest::Client;
use std::sync::Arc;

use crate::{
    errors::CustomError,
    models::user::{AccessToken, GithubUserInfo, Login},
    AppState,
};

```

```rust
let mut cookie = Cookie::new("ACCESS_TOKEN", access_token);
    cookie.set_path("/"); 
    cookie.set_max_age(Duration::days(7));
    cookie.set_http_only(true);

```

```rust
    let mut response = Response::Ok().body(format!("Hi, {}",user_info.login)); 

    // ignore error
    let _ = response.add_cookie(&cookie);

```

```toml
[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
cookie = "0.16.0"
dotenvy = "0.15.6"
env_logger = "0.10.0"
ntex = { version = "0.6.0", features = ["cookie", "tokio"] }
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "chrono",
] }

```
