### ISSUE TITLE
Fail to import ntex from git

### ISSUE THREAD

**Issue by Anivie** [ntex-rs/ntex#419]
I am trying to import this crate like this:
```toml
[dependencies.ntex]
git = "https://github.com/ntex-rs/ntex.git"
features = ["tokio", "tls-rustls", "rustls", "compress"]
```

But I will get this error:
```
error: failed to select a version for `ntex-io`.
    ... required by package `ntex-h2 v1.1.0`
    ... which satisfies dependency `ntex-h2 = "^1.1"` (locked to 1.1.0) of package `ntex v2.4.0 (https://github.com/ntex-rs/ntex.git#69f150e3)`
    ... which satisfies git dependency `ntex` of package `gpt-cat v0.1.0 (/home/gpt-cat)`
versions that meet the requirements `^2` (locked to 2.4.0) are: 2.4.0

all possible versions conflict with previously selected packages.

  previously selected package `ntex-io v2.5.0`
    ... which satisfies dependency `ntex-io = "^2.5"` of package `ntex v2.4.0 (https://github.com/ntex-rs/ntex.git#69f150e3)`
    ... which satisfies git dependency `ntex` of package `gpt-cat v0.1.0 (/home/gpt-cat)`

failed to select a version for `ntex-io` which could resolve this conflict
```
How can I fix this?Thanks!

**Comment by leon3s** [comment]
Hey, could you share you entire `Cargo.toml`

I tried with this one:

```toml
[package]
name = "test2"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.ntex]
git = "https://github.com/ntex-rs/ntex.git"
features = ["tokio", "tls-rustls", "rustls", "compress"]
```

And i didn't run into any issue
